'use strict';

// tests for <%= functionName %>
// Generated by serverless-mocha-plugin
const mod = require('../handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
const lambdaWrapper = mochaPlugin.lambdaWrapper;
let wrapped = lambdaWrapper.wrap(mod, {handler: 'aida'});
const sinon = require('sinon')

describe('get_passender_details', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    // Stub receiveMessageAsync
    let stub = sinon.stub(mod,'aida').callsArgWith(1, false, { statusCode: 200, body: JSON.stringify({result: "success"})});
    
    // Add all your stubbing stuff here
    //stub.resolves({ message: 'message from SQS' })
    return wrapped.run({
        method: 'GET',
       "queryStringParameters":{ "bookingnumber":"D34324",
        "firstname": "api2",
        "lastname": "K"}, stage: 'dev'
    
}).then((response) => {
    console.log(response);
      expect(response).to.not.be.empty;
      
    });
  });
});